version: "2"
services:
  tensorflow:
    container_name: tensorflow
    image: tensorflow/tensorflow:latest-py3-jupyter
    restart: unless-stopped
    ports: 
      - 8100:8888
    volumes:
      - /home/${user}/.notebooks:/tf/notebooks
      
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef
    restart: unless-stopped
    ports: 
      - 8101:8000
